import { GoogleGenerativeAI } from '@google/generative-ai';
import OpenAI from 'openai';

// Gemini client
let genAI = null;
let geminiModel = null;

const getGeminiModel = () => {
  if (!genAI) {
    genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    geminiModel = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
  }
  return geminiModel;
};

// OpenAI fallback client
let openaiClient = null;

const getOpenAI = () => {
  if (!openaiClient) {
    openaiClient = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }
  return openaiClient;
};

const callWithFallback = async (geminiCall, openaiCall) => {
  try {
    return await geminiCall();
  } catch (err) {
    console.warn('Gemini failed, falling back to OpenAI:', err.message);
    return await openaiCall();
  }
};

export const generateSummary = async (transcript) => {
  if (!transcript || transcript.length < 50) {
    return 'Transcript too short to summarize. Please provide more content.';
  }

  const prompt = `You are an expert at summarizing audio recordings and meetings.
Please analyze the following transcript and provide a clear, concise summary.

IMPORTANT: Only include sections that have actual content from the transcript. If something wasn't discussed or mentioned, DO NOT include that section at all. Never write things like "No decisions were made" or "Not mentioned" - simply omit that section entirely.

Include ONLY if present in the transcript:
- Main topics discussed
- Key points and takeaways
- Decisions made (only if actual decisions were made)
- Important information mentioned
- no "----" in between any lines, JUST USE SPACING

Format the summary with clear sections using markdown.

Transcript:
"""
${transcript}
"""

Please provide a well-structured summary (only including sections with actual content):`;

  return callWithFallback(
    async () => {
      const result = await getGeminiModel().generateContent(prompt);
      return result.response.text();
    },
    async () => {
      const res = await getOpenAI().chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [{ role: 'user', content: prompt }],
      });
      return res.choices[0].message.content;
    }
  );
};

export const generateMeetingMinutes = async (transcript, summary, title, outputLanguage = null) => {
  if (!transcript || transcript.length < 50) {
    return 'Transcript too short to generate minutes. Please provide more content.';
  }

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const langInstruction = outputLanguage
    ? `OUTPUT LANGUAGE: Write the entire meeting minutes in ${outputLanguage}. Translate all content into ${outputLanguage}. Keep markdown formatting intact.`
    : `OUTPUT LANGUAGE: Write in English.`;

  const prompt = `You are an expert at creating professional meeting minutes.
Please analyze the following transcript and generate comprehensive meeting minutes.

Meeting Title: ${title || 'Untitled Meeting'}
Date: ${date}

${summary ? `Existing Summary:\n${summary}\n` : ''}

Transcript:
"""
${transcript}
"""

${langInstruction}

IMPORTANT RULES:
1. ONLY include sections that have actual content from the transcript
2. If something wasn't discussed or mentioned, DO NOT include that section at all
3. Never write "No decisions were made", "None mentioned", "Not specified", "N/A" etc. - simply OMIT the entire section
4. Only include attendees/speakers if actual names were mentioned
5. Only include action items if specific tasks were discussed
6. Only include decisions if actual decisions were reached
7. Only include next steps if they were explicitly mentioned
8. Don't add any "----" in between any lines, JUST USE SPACING

Create professional meeting minutes in markdown format. Start with:

# Meeting Minutes

**Meeting:** ${title || 'Untitled Meeting'}
**Date:** ${date}

---

Then ONLY include these sections if they have actual content:
- Attendees/Speakers (only if names mentioned)
- Topics Discussed (main subjects covered)
- Key Discussion Points (important details)
- Decisions Made (only if decisions were actually made)
- Action Items (only if specific tasks mentioned)
- Next Steps (only if follow-ups discussed)

End with:
---
*Minutes generated by Echobit* (dont mention gemini )  `;

  return callWithFallback(
    async () => {
      const result = await getGeminiModel().generateContent(prompt);
      return result.response.text();
    },
    async () => {
      const res = await getOpenAI().chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [{ role: 'user', content: prompt }],
      });
      return res.choices[0].message.content;
    }
  );
};

export const extractActionItems = async (transcript) => {
  if (!transcript || transcript.length < 50) {
    return [];
  }

  const prompt = `Analyze the following transcript and extract any action items, tasks, or to-dos mentioned.

Transcript:
"""
${transcript}
"""

Return the action items as a JSON array with objects containing:
- "task": the action item description
- "assignee": who should do it (or "Unassigned" if not mentioned)
- "priority": "high", "medium", or "low" based on context
- "deadline": any mentioned deadline (or null if not mentioned)

Return ONLY the JSON array, no other text.`;

  const parseJSON = (text) => {
    const match = text.match(/\[[\s\S]*\]/);
    return match ? JSON.parse(match[0]) : [];
  };

  try {
    return await callWithFallback(
      async () => {
        const result = await getGeminiModel().generateContent(prompt);
        return parseJSON(result.response.text());
      },
      async () => {
        const res = await getOpenAI().chat.completions.create({
          model: 'gpt-4o-mini',
          messages: [{ role: 'user', content: prompt }],
        });
        return parseJSON(res.choices[0].message.content);
      }
    );
  } catch (error) {
    console.error('Action items extraction failed:', error);
    return [];
  }
};

export const generateTitle = async (transcript) => {
  if (!transcript || transcript.length < 20) {
    return `Recording ${new Date().toLocaleDateString()}`;
  }

  const prompt = `You are an expert at creating concise, descriptive titles.
Analyze the following transcript and generate a short, professional title (max 60 characters) that captures the main topic or purpose.

Rules:
- Keep it concise (3-8 words ideal)
- Make it descriptive and specific to the content
- Do NOT include dates or timestamps
- Do NOT use generic titles like "Meeting" or "Discussion"
- Do NOT use quotes around the title
- Return ONLY the title, nothing else

Transcript:
"""
${transcript.substring(0, 2000)}
"""

Title:`;

  try {
    return await callWithFallback(
      async () => {
        const result = await getGeminiModel().generateContent(prompt);
        return result.response.text().trim().replace(/^["']|["']$/g, '') || `Recording ${new Date().toLocaleDateString()}`;
      },
      async () => {
        const res = await getOpenAI().chat.completions.create({
          model: 'gpt-4o-mini',
          messages: [{ role: 'user', content: prompt }],
        });
        return res.choices[0].message.content.trim().replace(/^["']|["']$/g, '') || `Recording ${new Date().toLocaleDateString()}`;
      }
    );
  } catch (error) {
    console.error('Title generation failed:', error);
    return `Recording ${new Date().toLocaleDateString()}`;
  }
};

export default { generateSummary, generateMeetingMinutes, extractActionItems, generateTitle };
