// Minutes PDF export. html2canvas + jspdf are dynamically imported so they
// stay out of the main bundle (only loaded when a user actually exports).

import { formatMarkdownForPdf } from './markdown.js';
import { formatDate } from './format.js';

export const downloadMinutesPdf = async ({ title, createdAt, minutes, template }) => {
  const [{ jsPDF }, { default: html2canvas }] = await Promise.all([
    import('jspdf'),
    import('html2canvas'),
  ]);

  const marginMm = 5;
  const pageWidthMm = 210;
  const pageHeightMm = 297;
  const contentWidthMm = pageWidthMm - marginMm * 2;
  const contentHeightMm = pageHeightMm - marginMm * 2;
  const renderWidth = 800;

  const formattedContent = formatMarkdownForPdf(minutes, template.textColor);
  const headerStyle = template.headerStyle === 'centered' ? 'text-align: center;' : '';
  const headerBorder =
    template.headerStyle === 'underlined' ? `border-bottom: 3px solid ${template.accentColor};` : '';
  const headerBg =
    template.headerStyle === 'boxed'
      ? `background: ${template.accentColor}15; border-radius: 8px; padding: 20px; margin: -20px -20px 24px -20px;`
      : '';

  const tempContainer = document.createElement('div');
  tempContainer.style.cssText = `position: absolute; left: -9999px; top: 0; width: ${renderWidth}px; padding: 20px; background: #ffffff; font-family: system-ui, -apple-system, sans-serif; box-sizing: border-box;`;
  tempContainer.innerHTML = `
    <div style="${headerBg} ${headerBorder} padding-bottom: 20px; margin-bottom: 28px; ${headerStyle}">
      <h1 style="font-size: 26px; font-weight: 700; margin: 0 0 10px 0; color: ${template.textColor};">${title}</h1>
      <p style="font-size: 14px; color: #6b7280; margin: 0;">${formatDate(createdAt)}</p>
    </div>
    <div style="color: ${template.textColor}; line-height: 1.8; font-size: 14px;">
      ${formattedContent}
    </div>
    <div style="margin-top: 48px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; ${headerStyle}">
      Generated by Echobit • ${new Date().toLocaleDateString()}
    </div>
  `;
  document.body.appendChild(tempContainer);

  try {
    const canvas = await html2canvas(tempContainer, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    const imgWidthMm = contentWidthMm;
    const imgHeightMm = (canvas.height * contentWidthMm) / canvas.width;
    const pdf = new jsPDF('p', 'mm', 'a4');

    if (imgHeightMm <= contentHeightMm) {
      pdf.addImage(canvas.toDataURL('image/jpeg', 0.95), 'JPEG', marginMm, marginMm, imgWidthMm, imgHeightMm);
    } else {
      // Multi-page: slice the canvas per page
      const pxPerMm = canvas.width / contentWidthMm;
      const pageHeightPx = contentHeightMm * pxPerMm;
      const totalPages = Math.ceil(canvas.height / pageHeightPx);

      for (let i = 0; i < totalPages; i++) {
        if (i > 0) pdf.addPage();
        const srcY = i * pageHeightPx;
        const srcH = Math.min(pageHeightPx, canvas.height - srcY);

        const pageCanvas = document.createElement('canvas');
        pageCanvas.width = canvas.width;
        pageCanvas.height = srcH;
        const ctx = pageCanvas.getContext('2d');
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, pageCanvas.width, pageCanvas.height);
        ctx.drawImage(canvas, 0, srcY, canvas.width, srcH, 0, 0, canvas.width, srcH);

        pdf.addImage(pageCanvas.toDataURL('image/jpeg', 0.95), 'JPEG', marginMm, marginMm, imgWidthMm, srcH / pxPerMm);
      }
    }

    pdf.save(`${title}-minutes.pdf`);
  } finally {
    document.body.removeChild(tempContainer);
  }
};

export const downloadMarkdown = (title, minutes) => {
  const blob = new Blob([minutes], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title}-minutes.md`;
  a.click();
  URL.revokeObjectURL(url);
};
